### ISSUE TITLE
Add: Wist Preservation Associates to left column

### ISSUE THREAD

**Issue by KyleETC** [everythingtype/wistpreservation#8]
We'd like to add "Wist Preservation Associates" to the left column. It should left align with the navigation and be two breaks above the nav. The point size for the font should be the same. 

![screen shot 2015-01-08 at 10 50 45 am](https://cloud.githubusercontent.com/assets/6078640/5665131/3c8d83f2-9724-11e4-8eb1-b9a0c26f1f89.png)

**Comment by halfempty** [comment]
@KyleETC Take a look? http://wistpreservation.com/

**Comment by KyleETC** [comment]
Looks good. Thank you!
